global:
  local: false # When deploying to a local cluster (e.g.: kind cluster), set this to true.
  kind: false # Deprecated. Please use "global.local" instead. Will be removed later.
  ingressClass: "higress"

replicaCount: 1

image:
  repository: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/console
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

dnsPolicy: ClusterFirst
restartPolicy: Always
schedulerName: default-scheduler

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 250m
    memory: 512Mi

nodeSelector: {}
affinity: {}
tolerations: {}

web:
  login:
    prompt: "" # If set, a prompt message will be displayed on the login page.

admin:
  username: admin
  displayName: Admin
  password: "" # If set, the value will be used as the admin password for login.

chat:
  enabled: false
  endpoint: ""

certmanager:
  enabled: false
  replicas: 1
  image:
    repository: quay.io/jetstack
    tag: v1.11.0

o11y:
  enabled: false
  grafana:
    replicas: 1
    image:
      repository: grafana/grafana
      tag: 9.3.6
    port: 3000
    storage: 1Gi
    pvc:
      storageClassName: ""
  prometheus:
    replicas: 1
    image:
      repository: prom/prometheus
      tag: v2.40.7
    port: 9090
    storage: 1Gi
    pvc:
      storageClassName: ""
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
    securityContext:
      enabled: true
      runAsUser: 0
      fsGroup: 0
pvc:
  rwxSupported: true
