global:
  kind: false # When deploying to a local cluster (e.g.: kind cluster), set this to true.

replicaCount: 1

image:
  repository: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/console
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

dnsPolicy: ClusterFirst
restartPolicy: Always
schedulerName: default-scheduler

service:
  type: ClusterIP
  port: 8080

domain: console.higress.io
tlsSecretName: ""

ingress:
  className: "higress"
  annotations: {}
  paths:
    - path: /
      pathType: Prefix

resources:
  requests:
    cpu: 250m
    memory: 512Mi

nodeSelector: {}
affinity: {}
tolerations: {}

web:
  login:
    prompt: "" # If set, a prompt message will be displayed on the login page.

admin:
  username: admin
  displayName: Admin
  password:
    length: 8 # The length of random password generated during installation
    value: "" # If set, the value will be used as the admin password for login, and Helm won't generate a random password.

o11y:
  enabled: false
  grafana:
    replicas: 1
    image:
      repository: grafana/grafana
      tag: 9.3.6
    ingress:
      path: /grafana # Only pathType of Prefix is supported
    port: 3000
    storage: 1Gi
  prometheus:
    replicas: 1
    image:
      repository: prom/prometheus
      tag: v2.40.7
    ingress:
      path: /prometheus # Only pathType of Prefix is supported
    port: 9090
    storage: 1Gi
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
  certmanager:
    replicas: 1
    image:
      repository: quay.io/jetstack
      tag: v1.11.0
